name: MCP Safety Scan
description: Scan JS/TS/Python/Go repos for common MCP/tool-server security footguns (CORS, eval, exec, etc.)
author: Theodor N. Engøy

branding:
  icon: shield
  color: blue

inputs:
  path:
    description: Path to scan
    required: false
    default: .
  baseline:
    description: Baseline JSON file to ignore existing findings
    required: false
    default: ""
  ignore-dirs:
    description: Comma-separated list of directory basenames to ignore (e.g. test,__tests__,fixtures)
    required: false
    default: ""
  files-from:
    description: Newline-delimited list of files to scan (relative to path). If set, only these files are scanned.
    required: false
    default: ""
  include-tests:
    description: Include test files (e.g. *.test.*, *.spec.*, *_test.go, test_*.py). Default is false.
    required: false
    default: "false"
  format:
    description: Output format (text, json, sarif, github)
    required: false
    default: github
  fail-on:
    description: Fail threshold (critical, high, medium, low, info, none)
    required: false
    default: high
  sarif-output:
    description: SARIF filename (only used when format=sarif)
    required: false
    default: mcp-safety-scan.sarif

outputs:
  sarif_file:
    description: Path to the SARIF file (only set when format=sarif)

runs:
  using: composite
  steps:
    - shell: bash
      run: ${{ github.action_path }}/scripts/github-action.sh
      env:
        INPUT_PATH: ${{ inputs.path }}
        INPUT_BASELINE: ${{ inputs.baseline }}
        INPUT_IGNORE_DIRS: ${{ inputs['ignore-dirs'] }}
        INPUT_FILES_FROM: ${{ inputs['files-from'] }}
        INPUT_INCLUDE_TESTS: ${{ inputs['include-tests'] }}
        INPUT_FORMAT: ${{ inputs.format }}
        INPUT_FAIL_ON: ${{ inputs['fail-on'] }}
        INPUT_SARIF_OUTPUT: ${{ inputs['sarif-output'] }}
